name: Delete Old Auto Update Worker Runs

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日运行

jobs:
  delete-auto-update-worker-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Clean old workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 3
          keep_minimum_runs: 2
          token: ${{ secrets.PAT }}
